[global]
flavor = "mkdocs"
include = ["**/*.md"]
respect-gitignore = true

# Disable rules:
# MD014: Forces commands in codeblocks to show output
disable = ["MD014",]

[per-file-ignores]

[MD013]  # Line length
line_length = 999999
reflow = true
reflow_mode = "normalize"

[MD026]  # Remove punctuation at the end of headings
punctuation = ",;:"

[MD033]  # No inline HTML
allowed_elements = ["nospell",]  # pyspelling inline disable tag
